CREATE DATABASE hospital_index;
CREATE TABLE emergencies_2015 (
  CLUES TEXT,
  FECHAALTA DATETIME,
  EDAD INT,
  SEXO INT,
  DERHAB INT,
  TIPOURGENCIA INT,
  MOTATE INT,
  TIPOCAMA INT,
  ENVIADOA INT,
  FECHAINGRESO DATETIME,
  HORASESTANCIA INT,
  MES_ESTADISTICO INT 	
);

CREATE TABLE hospitals (
	CLUES TEXT,
	NOMBRE_TIPO_ESTABLECIMIENTO TEXT,
	NOMBRE_DE_TIPOLOGIA TEXT,
	TOTAL_DE_CAMAS INT,
    NOMBRE_DE_LA_UNIDAD TEXT,
    VIALIDAD TEXT,
    NUMERO_EXTERIOR TEXT,
    TIPO_DE_ASENTAMIENTO TEXT,
	ASENTAMIENTO TEXT,
    CODIGO_POSTAL INT,
	ESTATUS_DE_OPERACION TEXT,
    LONGITUD TEXT,
	LATITUD TEXT	
);